### ISSUE TITLE
Getting jibberish when using LANG_SWEDISH

### ISSUE THREAD

**Issue by mikasjoman** [jonathanpalma/react-native-tesseract-ocr#9] opened 2016-12-07 20:47 UTC
Hi, which files are neccessary for the OCR to work with Swedish? I downloaded the swe... file but it seems it doesn't work. Do I need the whole /tessdata folder with every language - or is it enough to just use a couple of them?

**Comment by jonathanpalma** [comment] 2016-12-10 21:25
@mikasjoman I'm really sorry for not replying but I'm traveling in Costa Rica and it makes me a bit difficult to connect to the internet 😢 But I will be working ASAP or when I'm already at home. Best regards. Pura Vida!! :costa_rica: ✌️

**Comment by mikasjoman** [comment] 2017-01-23 21:12
Hi - any progress on this? Do you know if there is any other way to do OCR with react native that makes the Swedish ÅÄÖ characters come out? I am trying to help my immigrant wife study medical Swedish, and she needs my app to be able to learn faster.

**Comment by jonathanpalma** [comment] 2017-02-13 01:18
Hi @mikasjoman 
I just released a new version that implements tess-two 6.2.0. I have also updated the documentation with the correct version of the trained data files because I found it could be one of the causes of the problem.

Please try with `react-native-tesseract-ocr@1.0.7` and let me know if it solves this issue. :v:

**Comment by jonathanpalma** [comment] 2017-02-13 01:27
@mikasjoman answering to your question "Do I need the whole /tessdata folder with every language - or is it enough to just use a couple of them?"

You just need the ".traineddata" files of the langs that you would like to use.

Also for this question check if you're not scaling or resizing your image because it could prevents a good text output quality. For more information about this check #11

**Comment by jonathanpalma** [comment] 2017-03-04 04:19
Since this issue hasn't had activity in a while I close it. In the same way if someone believes that the solutions raised don't meet the requirement, feel free to reopen

**Closed by jonathanpalma** 2017-03-04 04:19 UTC
